# Generated by Django 5.2.6 on 2025-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0002_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_to_learn',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
