# Generated by Django 5.2.6 on 2025-09-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0006_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
