# Generated by Django 5.2.6 on 2025-09-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0007_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
